language: r

install:
- git clone https://github.com/aviralg/r-3.4.0.git r
- cd r; ./configure; make; cd ..
- git clone https://github.com/aviralg/annotatr.git annotatr
- r/bin/R CMD INSTALL annotatr
- r/bin/R -e 'install.packages("testthat", repos="http://cran.us.r-project.org")'
- git clone https://github.com/aviralg/contractr.git contractr

script:
- r/bin/R CMD check contractr
