language: r

install:
- git clone https://github.com/aviralg/rant.git rant
- cd rant; ./configure; make -j; cd ..
- rant/bin/R -e 'install.packages("testthat", repos="http://cran.us.r-project.org")'
- rant/bin/R -e 'install.packages("devtools", repos="http://cran.us.r-project.org")'
- rant/bin/R -e 'install.packages("roxygen2", repos="http://cran.us.r-project.org")'
- git clone https://github.com/aviralg/annotatr.git annotatr
- rant/bin/R CMD INSTALL annotatr
- git clone https://github.com/aviralg/contractr.git contractr

script:
- cd contractr; ../rant/bin/R -e "devtools::test()"
