language: r

install:
- git clone https://github.com/aviralg/r-3.4.0.git r
- cd r; ./configure; sudo make install ; cd ..
- git clone https://github.com/aviralg/annotatr.git annotatr
- R CMD INSTALL annotatr
- R -e 'install.packages("testthat", repos="http://cran.us.r-project.org")'
- git clone https://github.com/aviralg/contractr.git contractr

script:
- R CMD check contractr
